Adding ability to use DatePicker or DateTimePicker in date filter column #1175
ral-facilities/datagateway pull request #1216
Opened 2022-04-06 14:35 UTC by sam-glendenning

## Description
Depending on if a filterByTime prop is passed, the date filter component will return either a KeyboardDatePicker or a KeyboardDateTimePicker. Thus, the admin download table now contains a KeyboardDateTimePicker for more accurate filtering of results.

This required some amendments to how time is passed to the backend date query. Previously, if a date was passed, it was assumed the time value would be 00:00:00 or 23:59:59, depending on startDate or endDate being changed. Now we must provide a time value if the user specifies one. 

Fortunately, the formatting for this is mostly done in the dateColumnFilter component, with one small change required to index.tsx. 

## Testing instructions
Because this is a change to the globally-used date filter, it is important to test date filtering in a variety of pages, including dataview, search, download and admin download. Currently, only the admin download table wants date and time filtering so make sure that other filters are date filter only and continue to work as expected. Finally, check to make sure that date and time values can be filtered on the admin download table correctly.

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
Closes #1175

2022-04-08 13:42 UTC, louise-davies requested changes
The regular download table also needs a time picker (I checked TopCAT and it has this)

The seconds bit is fine for now - I checked and MUIv5 has support for seconds in its datetimepicker so we can add support for that once that PR is merged in

2022-04-08 13:46 UTC, louise-davies commented on packages/datagateway-common/src/table/columnFilters/dateColumnFilter.component.tsx
> +            style={{ whiteSpace: 'nowrap' }}
It's probably worth extracting some of these props into a `commonProps` variable which we spread via `{...commonProps}` onto the 4 picker components we have to reduce code repetition

2022-04-19 09:19 UTC, louise-davies submitted a review, later dismissed
These changes now look good to me - please just check over the minor edit to the common types prop though (I made it so we use the actual library to define the prop types and extracted some more common props)

2022-04-19 15:25 UTC, sam-glendenning commented
> These changes now look good to me - please just check over the minor edit to the common types prop though (I made it so we use the actual library to define the prop types and extracted some more common props)

This looks much nicer, good spot. You'll have to review again due to a change in the base branch.

2022-04-20 08:19 UTC, louise-davies approved these changes

2022-04-20 08:25 UTC, merged