Create CITATION.cff
ral-facilities/datagateway pull request #1298
Opened 2022-06-21 15:08 UTC by agbeltran

## Description
Adding citation file; DOI will need to be added later.

## Testing instructions
- [ ] check text

## Agile board tracking
connect to #1297

2022-06-21 15:30 UTC, sam-glendenning requested changes
Just happened to notice this PR so sorry if this is ahead of a formal review but thought I'd quickly add:

2022-06-21 15:30 UTC, sam-glendenning commented on CITATION.cff
> +  given-names: "Swinbank"
These need to be swapped

2022-06-23 06:56 UTC, agbeltran commented on CITATION.cff
> +  given-names: "Swinbank"
@sam-glendenning thanks Sam!

2022-07-28 15:27 UTC, sam-glendenning approved these changes
@agbeltran this looks good but @louise-davies raised a concern in today's sprint review about whether or not this needed to go in the 1.0.0 release (which could cause difficulties since it's already been released). Apologies if I misremembered that, Louise, please feel free to jump in and clarify if so.

2022-08-17 09:23 UTC, agbeltran commented
@sam-glendenning @louise-davies let's merge this in at the first opportunity

2022-08-17 10:25 UTC, sam-glendenning commented
I'm happy with it, I believe Louise is too so will merge now

2022-08-17 10:25 UTC, merged