Feature/use icat5 file count #1457
ral-facilities/datagateway pull request #1499
Opened 2023-01-17 18:31 UTC by jounaidr

## Description
Enter a description of the changes here

## Testing instructions
Add a set up instructions describing how the reviewer should test the code

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage
- [ ] {more steps here}

## Agile board tracking
connect to #{issue number}

2023-01-19 09:47 UTC, jounaidr commented on packages/datagateway-common/src/app.types.tsx
> +  fileCount: number;
Are these okay being not possibly undefined with '?'

2023-01-19 16:53 UTC, jounaidr commented on packages/datagateway-common/src/detailsPanels/dls/visitDetailsPanel.component.tsx
> +  //TODO: Migrate to using entity size prop once dls has migrated to ICAT v5
This is the only place useInvestigationSize() query is used, can be removed once dls has migrated to ICAT V5

2023-01-24 22:57 UTC, jounaidr commented on packages/datagateway-common/src/detailsPanels/dls/visitDetailsPanel.component.tsx
> -              <b>
`fetch()` size button removed as redundant now, however I haven't test dls pages

2023-03-23 10:10 UTC, louise-davies requested changes
There's also some refactoring needed in `datagateway-download` - as `downloadCartTable` displays the size + file count of each entity in the cart to both display and accumulate the total size + file count. There's some efficiency  to be had in only going through and fetching each entity in the cart once, and using the resulting `Datafiles`/`Datasets`/`Investigations` to derive both the sizes and counts - whereas currently we're sending two queries for each entity. lmk if you want to chat with me to explain this better.

Otherwise, just some minor comments and some things pending on knowing what DLS want

2023-05-17 14:20 UTC, louise-davies commented
I've addressed the review comments I had previously made and ensured all the tests are passing - we're now just waiting on a decision from Diamond on what they want to show in their views

2024-01-18 14:19 UTC, louise-davies commented
Dataset count replaced with investigation filesize

Dataset datafile count replaced with the ICAT 5 equivalent, and add a size column

Waiting confimation from Kirsty and Greg

2024-02-06 13:19 UTC, kaperoo approved these changes
Looks good to me 👍

2024-02-06 15:53 UTC, louise-davies approved these changes

2024-02-06 15:53 UTC, merged