Citation formatter on ISIS study landing pages #868
ral-facilities/datagateway pull request #976
Opened 2021-12-02 15:38 UTC by joelvdavies

## Description
Adds a citation formatter to the ISIS study landing page when a DOI is defined. A drop down menu can then be used to select a format to use and then displays it with a 'Copy citation' button to copy the citation. The allowed formats can be configured using the language file. The possible formats can be found here: https://github.com/citation-style-language/styles.

This is still a draft.
TODO:
- [ ] Catch errors for invalid DOI/in case the is a problem reaching datacite and display an error message to the user
- [ ] Add unit/e2e tests

## Testing instructions

- [ ] Review code
- [ ] Check Actions build
- [ ] Review changes to test coverage

## Agile board tracking
connect to #{issue number}

2021-12-08 08:54 UTC, joelvdavies commented
After speaking to Louise, I have updated this to replace the old citation using the `chicago-author-date` format as a default which is fetched on page load. This can also be configured through `default.json` as the default is taken as the first defined in the list of formats. Here are some updated screenshots:
![image](https://user-images.githubusercontent.com/90245114/145178334-22b8e515-7da7-4a41-a70b-50bea5d9f9a8.png)
![image](https://user-images.githubusercontent.com/90245114/145178413-3111e72f-a475-4f2d-a6f2-97ae51f90e00.png)

2021-12-09 11:03 UTC, louise-davies reviewed
This looks good! The only concern I have is we're basically ignoring ISIS's recommendation here: https://www.isis.stfc.ac.uk/Pages/Digital-Object-Identifiers-(DOIs)-for-ISIS-Data.aspx. I can't seem to find any format that matches this - but perhaps we can have a "default" dropdown option which doesn't fetch via the citation formatter API and instead does similar to what the old one does: https://github.com/ral-facilities/common-doi/blob/0d603ca1311df1f287fbd6af742ecf9e78ee6ffc/src/main/java/uk/ac/stfc/doi/model/DOIModel.java#L242

Or maybe I'm overthinking this - it just seems wrong to not offer ISIS's preferred format.

2021-12-15 09:31 UTC, louise-davies requested changes
I believe we also need the formatter on the investigation landing pages to match with what the current landing pages offer: https://data.isis.stfc.ac.uk/doi/INVESTIGATION/85007962/

2021-12-16 09:05 UTC, joelvdavies commented
I have also just modified it to display the same as before in cases where there is no DOI e.g.
![image](https://user-images.githubusercontent.com/90245114/146341087-52cfb885-3a28-402f-ae7d-6286f1eac227.png)
as this matches TopCAT.

2021-12-16 11:16 UTC, louise-davies requested changes

2021-12-16 11:16 UTC, louise-davies commented on packages/datagateway-dataview/src/views/landing/isis/isisInvestigationLanding.component.tsx
> +                  ? studyInvestigation[0]?.study?.startDate
The study very often does not have a start date itself and instead it gets the start date from the underlying investigation. So here this should just be the investigation startDate

2022-01-05 09:41 UTC, louise-davies approved these changes

2022-01-05 10:38 UTC, merged